#Question no. 1:-Write a python program which searches all the product under a particular product from www.amazon.in. The 
product to be searched will be taken as input from user. For e.g. If user input is ‘guitar’. Then search for 
guitars.

In [11]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\91935\anaconda3\lib\site-packages (4.16.0)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\91935\anaconda3\lib\site-packages (from selenium) (2022.12.7)
Requirement already satisfied: trio~=0.17 in c:\users\91935\anaconda3\lib\site-packages (from selenium) (0.24.0)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\91935\anaconda3\lib\site-packages (from selenium) (1.26.14)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\91935\anaconda3\lib\site-packages (from selenium) (0.11.1)
Requirement already satisfied: cffi>=1.14 in c:\users\91935\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: idna in c:\users\91935\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: attrs>=20.1.0 in c:\users\91935\anaconda3\lib\site-packages (from trio~=0.17->selenium) (22.1.0)
Requirement already satisfied: sortedcontainers in c:\users\91935\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: outcome in c:\users\91935\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\91935\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0)
Requirement already satisfied: exceptiongroup in c:\users\91935\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: wsproto>=0.14 in c:\users\91935\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\91935\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\91935\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\91935\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [25]:
#Import the required modules:-

import selenium
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import NoSuchElementException, StaleElementReferenceException
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import time
import pandas as pd
from bs4 import BeautifulSoup
import requests
import re
from selenium.webdriver.support.ui import WebDriverWait

In [26]:
#Create a webdriver object:-

driver=webdriver.Chrome()

In [27]:
#Go to the amazon website:-

driver.get('https://www.amazon.in/')

In [28]:
#Get the input from the user:-

product=input("Enter the product name: ")

Enter the product name: guitar

In [29]:
#Find the search box element and enter the product name:-

search_box= driver.find_element(By.ID,"twotabsearchtextbox")
search_box.send_keys(product)
search_box.send_keys(Keys.RETURN)

#Question no.2:-In the above question, now scrape the following details of each product listed in first 3 pages of your search 
results and save it in a data frame and csv. In case if any product has less than 3 pages in search results then 
scrape all the products available under that product name. Details to be scraped are: "Brand 
Name", "Name of the Product", "Price", "Return/Exchange", "Expected Delivery", "Availability" and 
“Product URL”. In case, if any of the details are missing for any of the product then replace it by “-“.

In [30]:
#scrape all product urls:-
product_urls=[]
start=0
end=3

#for loop for scraping 3 page:-
for page in range(start,end):
    
    #scraping urls:-
    url=driver.find_elements(By.XPATH,'//a[@class="a-link-normal s-underline-text s-underline-link-text s-link-style a-text-normal"]')
    
    for i in url:
        product_urls.append(i.get_attribute("href"))
    nxt_button=driver.find_elements(By.XPATH,'//a[@class="s-pagination-item s-pagination-next s-pagination-button s-pagination-separator"]')
    time.sleep(2)

In [31]:
len(product_urls)

195

In [32]:
Brand=[]
Product_name=[]
Price=[]
Return_exchange=[]
Delivery=[]
Availability=[]
Product_url=[]

In [33]:
#Loop for every guitar in the list:-

for url in product_urls:
    driver.get(url)
    time.sleep(2)
    
    try:
        brand=driver.find_element(By.XPATH,'//tr[@class="a-spacing-small po-brand"]/td[2]/span')
        Brand.append(brand.text)
    except NoSuchElementException:
        Brand.append("-")
        
    try:
        name=driver.find_element(By.XPATH,'//span[@class="a-size-large product-title-word-break"]')
        Product_name.append(name.text)
    except NoSuchElementException:
        Product_name.append("-")
        
    try:
        price=driver.find_element(By.XPATH,'.//span[@class="a-price-whole"]')
        Price.append(price.text)
    except NoSuchElementException:
        Price.append("-")
        
    try:
        return_exchange=driver.find_element(By.XPATH,'//li[@class="a-carousel-card tw-scroll-carousel-element"]/div/span')
        Return_exchange.append(return_exchange.text)
    except NoSuchElementException:
        Return_exchange.append("-")
        
    try:
        delivery=driver.find_element(By.XPATH,'//div[@class="a-spacing-base"]/span')
        Delivery.append(delivery.text)
    except NoSuchElementException:
        Delivery.append("-")
        
    try:
        availability=driver.find_element(By.XPATH,'//span[@class="a-size-medium a-color-success"]')
        Availability.append(availability.text)
    except NoSuchElementException:
        Availability.append("-")
        
    try:
        url=driver.find_element(By.XPATH,'//a[@class="a-link-normal s-underline-text s-underline-link-text s-link-style a-text-normal"]').get_attribute("href")
        Product_url.append(url)
    except NoSuchElementException:
        Product_url.append("-")

In [34]:
#Creating a data frame from the scraped data:-

df=pd.DataFrame({'Brand Name':Brand,'Product Name':Product_name,'Product Price':Price,'Return_Exchange':Return_exchange,'Product Delivery':Delivery,'Product Availability':Availability,'Product URLs':Product_url})


#Saving the dataframe as a CSV file:-

df.to_csv("amazon_products.csv",index=False)

df

,Brand Name,Product Name,Product Price,Return_Exchange,Product Delivery,Product Availability,Product URLs
0,Kadence,Kadence Frontier guitar with Online Guitar lea...,"4,499",7 days Replacement,"FREE delivery Wednesday, 14 February. Details",In stock,-
1,Kadence,"Kadence rosewood Guitar Frontier Series, Elect...","5,499",7 days Replacement,"FREE delivery Wednesday, 14 February. Details",In stock,-
2,Kadence,Kadence Slowhand Premium Jumbo Semi Acoustic G...,"9,999",7 days Replacement,"FREE delivery Wednesday, 14 February. Details",In stock,-
3,Henrix,Henrix 38C 38 Inch Cutaway Acoustic Guitar Wit...,"3,099",7 days Replacement,"FREE delivery Thursday, 15 February. Details",In stock,-
4,JUAREZ,"Juârez Acoustic Guitar, 38 Inch Cutaway, 038C ...","2,199",7 days Replacement,"FREE delivery Thursday, 15 February. Details",In stock,-
...,...,...,...,...,...,...,...
190,VAULT,Vault DA20 Dreadnought Acoustic Guitar With Gi...,"4,899",7 days Replacement,"FREE delivery Thursday, 15 February. Details",In stock,-
191,Gum-Tea,"Acoustic Guitar, 39 Inch Cutaway, 039C with Ba...","4,996",-,"FREE delivery Thursday, 15 February. Order wit...",-,-
192,blueberry,"BLUEBERRY D38, Truss Rod Acoustic Guitar Kit w...","2,890",7 days Replacement,"FREE delivery Saturday, 17 February. Order wit...",In stock,-
193,blueberry,"BLUEBERRY B-40, Acoustic Guitar Kit Inbuilt Tr...","4,590",7 days Replacement,"FREE delivery Saturday, 17 February. Order wit...",In stock,-
194,Mackie,Mackie Producer Bundle with Onyx Producer inte...,"27,549",7 days Replacement,"FREE delivery Thursday, 15 February. Details",-,-

#Question no. 3:- Write a python program to access the search bar and search button on images.google.com and scrape 10 
images each for keywords ‘fruits’, ‘cars’ and ‘Machine Learning’, ‘Guitar’, ‘Cakes’.

In [29]:
#Import selenium and webdriver:-

import selenium
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import NoSuchElementException
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import time
import pandas as pd
import requests

In [30]:
#Create a webdriver:-

driver=webdriver.Chrome()

In [31]:
#Go to webpage:-
driver.get("https://images.google.com/")

In [32]:
#Create a list of Keywords to search:-

keywords=["Fruits","Cars","Machine_Learning","Guitar","Cakes"]

In [33]:
#Loop through the keywords:-

for keyword in keywords:
    
    #Go to webpage:-
    driver.get("https://images.google.com/")
    
    #Find the search bar element:-
    search_bar=driver.find_element(By.NAME,'q')
    
    #clear the search bar:-
    search_bar.clear()
    
    #Enter the keyword and press enter:-
    search_bar.send_keys(keyword)
    search_bar.send_keys(Keys.RETURN)

In [34]:
for _ in range(20):
    driver.execute_script("window.scrollBy(0,500)")
    
images=driver.find_elements(By.XPATH,'//img[@class="rg_i Q4LuWd"]')

img_urls=[]
for image in images:
    source=image.get_attribute("src")
    if source is not None:
        if(source[0:4]=='http'):
            img_urls.append(source)

In [39]:
for i in range(len(img_urls)):
    if i > 10:
        break
        By.XPATH,
    print("Downloading {0} of {1} images" .format(i, 10))
    
    response=requests.get(img_urls[i])
    file=open(r"C:\Users\91935\Desktop\Data Trained Education_files"+str(i)+".jpg","wb")
    file.write(response.content)

Downloading 0 of 10 images
Downloading 1 of 10 images
Downloading 2 of 10 images
Downloading 3 of 10 images
Downloading 4 of 10 images
Downloading 5 of 10 images
Downloading 6 of 10 images
Downloading 7 of 10 images
Downloading 8 of 10 images
Downloading 9 of 10 images
Downloading 10 of 10 images

#Question no.4:-Write a python program to search for a smartphone(e.g.: Oneplus Nord, pixel 4A, etc.) on www.flipkart.com
and scrape following details for all the search results displayed on 1st page. Details to be scraped: “Brand 
Name”, “Smartphone name”, “Colour”, “RAM”, “Storage(ROM)”, “Primary Camera”, 
“Secondary Camera”, “Display Size”, “Battery Capacity”, “Price”, “Product URL”. Incase if any of the 
details is missing then replace it by “- “. Save your results in a dataframe and CSV

In [175]:
#Importing the required libraries:-

import selenium
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import NoSuchElementException
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import time
import pandas as pd

In [176]:
#Creating a webdriver object:-

driver=webdriver.Chrome()

In [177]:
#searching for a smartphone on flipkart.com:-

smartphone= input("Enter the searching name: ")
driver.get("https://www.flipkart.com/search?q="+smartphone)

Enter the searching name: smartphone

In [178]:
#Creating empty lists to store the scraped data:-

brand_name=[]
smartphone_name=[]
colour=[]
ram=[]
storage=[]
primary_camera=[]
secondary_camera=[]
display_size=[]
battery_capacity=[]
price=[]
product_url=[]

In [179]:
#Scraping the details for all the search results on the first page:-

products=driver.find_elements(By.CLASS_NAME,'_1AtVbE')

In [180]:
#Looping through each product:-

for product in products:
    
    #Getting the product URL:-
    try:
        link=product.find_element(By.XPATH,'.//a[@class="_1fQZEK"]')
        product_url.append(link.get_attribute("href"))
    except NoSuchElementException:
        product_url.append("-")
    
    
    #Getting the brand name:-
    try:
        brand=product.find_element(By.XPATH,".//div[@class='_4rR01T']").text.split()[0]
    except NoSuchElementException:
        brand="-"
    brand_name.append(brand)
    
    
    
    #Getting the smartphone name:-
    try:
        smartphone=" ".join(product.find_element(By.XPATH,".//div[@class='_4rR01T']").text.split()[1:])
    except NoSuchElementException:
        smartphone="-"
    smartphone_name.append(smartphone)
    
    
    #Getting the colour name:-
    try:
        colr=product.find_element(By.XPATH,"div/div/div/a/div[2]/div[1]/div[1]").text
    except NoSuchElementException:
        colr="-"
    colour.append(colr)
    
    
    #Getting the RAM and ROM element:-
    try:
        RAM_ROM=product.find_element(By.XPATH,"div/div/div/a/div[2]/div[1]/div[3]/ul/li[1]").text.split("|")
        RAM=RAM_ROM[0].strip()
        ROM=RAM_ROM[-1].strip()
    except NoSuchElementException:
        RAM="-"
        ROM="-"
    ram.append(RAM)
    storage.append(ROM)
    
    
    
    
    #Getting the primary and secondary camera:-
    try:
        primary_secondary=product.find_element(By.XPATH,"div/div/div/a/div[2]/div[1]/div[3]/ul/li[3]").text.split("|")
        primary=primary_secondary[0].strip()
        secondary=primary_secondary[-1].strip()
        
    except NoSuchElementException:
        primary="-"
        secondary="-"
    primary_camera.append(primary)
    secondary_camera.append(secondary)
    
    
    
    #Getting the display size:-
    try:
        display=product.find_element(By.XPATH,"div/div/div/a/div[2]/div[1]/div[3]/ul/li[2]").text
    except NoSuchElementException:
        display="-"
    display_size.append(display)
    
    
    #Getting the battery capacity:-
    try:
        battery=product.find_element(By.XPATH,"div/div/div/a/div[2]/div[1]/div[3]/ul/li[4]").text
    except NoSuchElementException:
        battery="-"
    battery_capacity.append(battery)
    
    
    #Getting the price:-
    try:
        pri=product.find_element(By.CLASS_NAME,'_30jeq3').text
    except NoSuchElementException:
        pri="-"
    price.append(pri)

In [181]:
#Creating a data frame from the scraped data:-

df=pd.DataFrame({'Brand Name':brand_name,'Smartphone Name':smartphone_name,'Colour':colour,'RAM':ram,'Storage(ROM)':storage,'Primary Camera':primary_camera,'Secondary Camera':secondary_camera,'Display Size':display_size,'Battery Capacity':battery_capacity,'Price':price,'Product URL':product_url})


#Saving the dataframe as a CSV file:-

df.to_csv("flipkart_smartphones.csv",index=False)

df

,Brand Name,Smartphone Name,Colour,RAM,Storage(ROM),Primary Camera,Secondary Camera,Display Size,Battery Capacity,Price,Product URL
0,-,-,-,-,-,-,-,-,-,-,-
1,-,-,-,-,-,-,-,-,-,-,-
2,-,-,-,-,-,-,-,-,-,-,-
3,Motorola,"G34 5G (Ocean Green, 128 GB)","Motorola G34 5G (Ocean Green, 128 GB)",8 GB RAM,128 GB ROM,50MP + 2MP,16MP Front Camera,16.51 cm (6.5 inch) HD+ Display,5000 mAh Battery,"₹11,999",https://www.flipkart.com/motorola-g34-5g-ocean...
4,POCO,"C51 (Royal Blue, 64 GB)","POCO C51 (Royal Blue, 64 GB)",4 GB RAM,Expandable Upto 1 TB,8MP Dual Rear Camera,5MP Front Camera,16.56 cm (6.52 inch) HD+ Display,5000 mAh Battery,"₹5,499",https://www.flipkart.com/poco-c51-royal-blue-6...
5,Motorola,"G34 5G (Ocean Green, 128 GB)","Motorola G34 5G (Ocean Green, 128 GB)",4 GB RAM,128 GB ROM,50MP + 2MP,16MP Front Camera,16.51 cm (6.5 inch) HD+ Display,5000 mAh Battery,"₹10,999",https://www.flipkart.com/motorola-g34-5g-ocean...
6,POCO,"C51 - Locked with Airtel Prepaid (Royal Blue, ...",POCO C51 - Locked with Airtel Prepaid (Royal B...,4 GB RAM,Expandable Upto 1 TB,8MP Dual Rear Camera,5MP Front Camera,16.56 cm (6.52 inch) HD+ Display,5000 mAh Battery,"₹4,999",https://www.flipkart.com/poco-c51-locked-airte...
7,vivo,"T2x 5G (Aurora Gold, 128 GB)","vivo T2x 5G (Aurora Gold, 128 GB)",4 GB RAM,128 GB ROM,50MP + 2MP,8MP Front Camera,16.71 cm (6.58 inch) Full HD+ Display,5000 mAh Battery,"₹11,999",https://www.flipkart.com/vivo-t2x-5g-aurora-go...
8,vivo,"T2x 5G (Glimmer Black, 128 GB)","vivo T2x 5G (Glimmer Black, 128 GB)",6 GB RAM,128 GB ROM,50MP + 2MP,8MP Front Camera,16.71 cm (6.58 inch) Full HD+ Display,5000 mAh Battery,"₹12,999",https://www.flipkart.com/vivo-t2x-5g-glimmer-b...
9,vivo,"T2x 5G (Marine Blue, 128 GB)","vivo T2x 5G (Marine Blue, 128 GB)",4 GB RAM,128 GB ROM,50MP + 2MP,8MP Front Camera,16.71 cm (6.58 inch) Full HD+ Display,5000 mAh Battery,"₹11,999",https://www.flipkart.com/vivo-t2x-5g-marine-bl...
10,vivo,"T2x 5G (Marine Blue, 128 GB)",,-,-,-,-,-,-,"₹12,999",https://www.flipkart.com/vivo-t2x-5g-marine-bl...
11,vivo,"T2x 5G (Aurora Gold, 128 GB)",,-,-,-,-,-,-,"₹12,999",https://www.flipkart.com/vivo-t2x-5g-aurora-go...
12,vivo,"T2x 5G (Glimmer Black, 128 GB)","vivo T2x 5G (Glimmer Black, 128 GB)",8 GB RAM,128 GB ROM,50MP + 2MP,8MP Front Camera,16.71 cm (6.58 inch) Full HD+ Display,5000 mAh Battery,"₹14,999",https://www.flipkart.com/vivo-t2x-5g-glimmer-b...
13,vivo,"T2x 5G (Aurora Gold, 128 GB)","vivo T2x 5G (Aurora Gold, 128 GB)",8 GB RAM,128 GB ROM,50MP + 2MP,8MP Front Camera,16.71 cm (6.58 inch) Full HD+ Display,5000 mAh Battery,"₹14,999",https://www.flipkart.com/vivo-t2x-5g-aurora-go...
14,vivo,"T2x 5G (Marine Blue, 128 GB)","vivo T2x 5G (Marine Blue, 128 GB)",8 GB RAM,128 GB ROM,50MP + 2MP,8MP Front Camera,16.71 cm (6.58 inch) Full HD+ Display,5000 mAh Battery,"₹14,999",https://www.flipkart.com/vivo-t2x-5g-marine-bl...
15,vivo,"T2x 5G (Glimmer Black, 128 GB)","vivo T2x 5G (Glimmer Black, 128 GB)",4 GB RAM,128 GB ROM,50MP + 2MP,8MP Front Camera,16.71 cm (6.58 inch) Full HD+ Display,5000 mAh Battery,"₹11,999",https://www.flipkart.com/vivo-t2x-5g-glimmer-b...
16,Motorola,"g54 5G (Pearl Blue, 128 GB)","Motorola g54 5G (Pearl Blue, 128 GB)",8 GB RAM,Expandable Upto 1 TB,50MP (OIS) + 8MP,16MP Front Camera,16.51 cm (6.5 inch) Full HD+ Display,6000 mAh Battery,"₹13,999",https://www.flipkart.com/motorola-g54-5g-pearl...
17,Motorola,"g54 5G (Midnight Blue, 128 GB)","Motorola g54 5G (Midnight Blue, 128 GB)",8 GB RAM,Expandable Upto 1 TB,50MP (OIS) + 8MP,16MP Front Camera,16.51 cm (6.5 inch) Full HD+ Display,6000 mAh Battery,"₹13,999",https://www.flipkart.com/motorola-g54-5g-midni...
18,Motorola,"g54 5G (Mint Green, 256 GB)","Motorola g54 5G (Mint Green, 256 GB)",12 GB RAM,Expandable Upto 1 TB,50MP (OIS) + 8MP,16MP Front Camera,16.51 cm (6.5 inch) Full HD+ Display,6000 mAh Battery,"₹15,999",https://www.flipkart.com/motorola-g54-5g-mint-...
19,POCO,"M6 5G (Orion Blue, 128 GB)","POCO M6 5G (Orion Blue, 128 GB)",4 GB RAM,Expandable Upto 1 TB,50MP Rear Camera,50MP Rear Camera,17.12 cm (6.74 inch) HD+ Display,5000 mAh Battery,"₹9,999",https://www.flipkart.com/poco-m6-5g-orion-blue...
20,realme,"12 Pro 5G (Navigator Beige, 256 GB)","realme 12 Pro 5G (Navigator Beige, 256 GB)",8 GB RAM,256 GB ROM,50MP + 8MP + 32MP,16MP Front Camera,17.02 cm (6.7 inch) Full HD+ Display,5000 mAh Battery,"₹26,999",https://www.flipkart.com/realme-12-pro-5g-navi...
21,realme,"12 Pro 5G (Submarine Blue, 256 GB)","realme 12 Pro 5G (Submarine Blue, 256 GB)",8 GB RAM,256 GB ROM,50MP + 8MP + 32MP,16MP Front Camera,17.02 cm (6.7 inch) Full HD+ Display,5000 mAh Battery,"₹26,999",https://www.flipkart.com/realme-12-pro-5g-subm...
22,realme,"12 Pro 5G (Submarine Blue, 128 GB)","realme 12 Pro 5G (Submarine Blue, 128 GB)",8 GB RAM,128 GB ROM,50MP + 8MP + 32MP,16MP Front Camera,17.02 cm (6.7 inch) Full HD+ Display,5000 mAh Battery,"₹25,999",https://www.flipkart.com/realme-12-pro-5g-subm...
23,realme,"12 Pro 5G (Navigator Beige, 128 GB)","realme 12 Pro 5G (Navigator Beige, 128 GB)",8 GB RAM,128 GB ROM,50MP + 8MP + 32MP,16MP Front Camera,17.02 cm (6.7 inch) Full HD+ Display,5000 mAh Battery,"₹25,999",https://www.flipkart.com/realme-12-pro-5g-navi...
24,realme,"11x 5G (Midnight Black, 128 GB)","realme 11x 5G (Midnight Black, 128 GB)",8 GB RAM,Expandable Upto 2 TB,64MP + 2MP,8MP Front Camera,17.07 cm (6.72 inch) Full HD+ Display,5000 mAh Battery,"₹15,999",https://www.flipkart.com/realme-11x-5g-midnigh...
25,realme,"11x 5G (Midnight Black, 128 GB)","realme 11x 5G (Midnight Black, 128 GB)",6 GB RAM,Expandable Upto 2 TB,64MP + 2MP,8MP Front Camera,17.07 cm (6.72 inch) Full HD+ Display,5000 mAh Battery,"₹14,999",https://www.flipkart.com/realme-11x-5g-midnigh...
26,realme,"11x 5G (Purple Dawn, 128 GB)",,-,-,-,-,-,-,"₹14,999",https://www.flipkart.com/realme-11x-5g-purple-...
27,-,-,-,-,-,-,-,-,-,-,-
28,-,-,-,-,-,-,-,-,-,-,-
29,-,-,-,-,-,-,-,-,-,"₹15,999",-
30,-,-,-,-,-,-,-,-,-,-,-

Question no. 5:-Write a program to scrap geospatial coordinates (latitude, longitude) of a city searched on google maps.

In [9]:
#Importing the required libraries:-

import selenium
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import NoSuchElementException
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import time
import pandas as pd
import re

In [10]:
#Creating a webdriver object:-

driver=webdriver.Chrome()

In [11]:
#Go to webpage:-

driver.get("https://www.google.co.in/maps")

In [12]:
#Find the search box element:-

search_box=driver.find_element(By.ID,"searchboxinput")

In [13]:
#Enter the city name and press enter:-

city="Nashik"
search_box.send_keys(city)
search_box.send_keys(Keys.RETURN)

In [14]:
#wait for page to load:-

driver.implicitly_wait(10)

In [15]:
#Get the current URL:-

url= driver.current_url

In [16]:
#Extract the latitude and longitude from the URL using regular expressions:-

pattern= r"@(-?\d+\.\d+),(-?\d+\.\d+)"
match= re.search(pattern,url)

In [17]:
#If a match is found, print the coordinates:-

if match:
    latitude=match.group(1)
    longitude=match.group(2)
    print(f"The geospatial coordinates of {city} are: ")
    print(f"Latitude: {latitude}")
    print(f"Longitude: {longitude}")
else:
    print("Could not find the coordinates")

The geospatial coordinates of Nashik are:
Latitude: 19.9908869
Longitude: 73.6386623

#Question no. 6:- Write a program to scrap all the available details of best gaming laptops from digit.in.

In [13]:
#Importing the required libraries:-

import selenium
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import NoSuchElementException
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import time
import pandas as pd
import re

In [14]:
#Create a driver object:-

driver=webdriver.Chrome()

In [15]:
#Go to webpage:-

driver.get("https://www.digit.in/top-products/best-gaming-laptops-40.html")

In [16]:
#scrape all product urls:-
product_urls=[]
#scraping urls:-
url=driver.find_elements(By.XPATH,'//h3[@class="font130 mt0 mb10 mobilesblockdisplay "]/a')
for i in url:
    product_urls.append(i.get_attribute("href"))

In [17]:
len(product_urls)

7

In [18]:
#Creating empty list:-

Laptop_Name=[]
Operating_sys=[]
Display=[]
Processor=[]
Storage=[]

In [19]:
#Loop for every guitar in the list:-

for url in product_urls:
    driver.get(url)
    time.sleep(2)
        
    
    
    try:
        laptop_name=driver.find_element(By.XPATH,'//h1[@class="floatleft tabletblockdisplay pr20 "]')
        Laptop_Name.append(laptop_name.text)
    except NoSuchElementException:
        Laptop_Name.append("-")
        
    try:
        system=driver.find_element(By.XPATH,'//div[@class="specs_details "]//li[1]')
        Operating_sys.append(system.text)
    except NoSuchElementException:
        Operating_sys.append("-")
        
    try:
        display=driver.find_element(By.XPATH,'//div[@class="specs_details "]//li[4]')
        Display.append(display.text)
    except NoSuchElementException:
        Display.append("-")
        
    try:
        processor=driver.find_element(By.XPATH,'//div[@class="specs_details "]//li[2]')
        Processor.append(processor.text)
    except NoSuchElementException:
        Processor.append("-")
        
    try:
        storage=driver.find_element(By.XPATH,'//div[@class="specs_details "]//li[3]')
        Storage.append(storage.text)
    except NoSuchElementException:
        Storage.append("-")

In [20]:
#Creating a data frame from the scraped data:-

df=pd.DataFrame({'Laptop Name':Laptop_Name,'Operating System':Operating_sys,'Laptop display':Display,'Laptop Processor':Processor,'storage Capacity':Storage})


df

,Laptop Name,Operating System,Laptop display,Laptop Processor,storage Capacity
0,HP Omen 17-Ck2008TX 13th Gen Core I7-13700HX,Operating System (With\nWindows 11 Home,Display Size (In Inches)\n17.3,Processor Model Name\n13th Gen Intel Core I7-1...,Storage Drive Capacity\n1 TB
1,MSI GT77 Titan 12UHS-054IN 12th Gen Core I9-12...,-,-,-,-
2,Lenovo Legion 5i Pro 12th Gen Core I7-12700H (...,Operating System (With\nWindows 11 Home,Display Size (In Inches)\n16,Processor Model Name\n12th Gen Intel Core I7-1...,Storage Drive Capacity\n1 TB
3,ASUS ROG Strix Scar 18 G834JZ-N5041WS 13th Gen...,-,-,-,-
4,Acer Predator Helios Neo 16 13th Gen Core I7-1...,Operating System (With\nWindows 11 Home,Display Size (In Inches)\n16,Processor Model Name\n13th Gen Intel Core I7-1...,Storage Drive Capacity\n1 TB
5,ASUS ROG Zephyrus G14 Ryzen 9-6900HS (GA402RJZ...,-,-,-,-
6,MSI Cyborg 15 12th Gen Core I7-12650H (A12VF-2...,-,-,-,-

#Question no.7:- Write a python program to scrape the details for all billionaires from www.forbes.com. Details to be scrapped: 
“Rank”, “Name”, “Net worth”, “Age”, “Citizenship”, “Source”, “Industry”.

In [28]:
# Import the required modules
import requests
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException
import time

In [29]:
#Create a driver object:-

driver=webdriver.Chrome()

In [30]:
#Go to webpage:-

driver.get("https://www.forbes.com/billionaires/")

In [31]:
#Scraping required data from the web page
#Creating empty lists:-

rank=[]
person_name=[]
net_worth=[]
age=[]
citizenship=[]
source=[]
industry=[]

In [32]:
#Scraping information for first row:-

#scraping first rank:-
rank_tag=driver.find_elements(By.XPATH,'/html/body/div[1]/div[2]/div[3]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div/div[1]/div')
for rnk in rank_tag:
    rank.append(rnk.text)

In [33]:
print(rank)

['1', '', 'Bernard Arnault oversees the LVMH empire of 75 fashion and cosmetics brands, including Louis Vuitton and Sephora.\nFULL PROFILE']

In [34]:
#scraping name:-
name_tag=driver.find_elements(By.XPATH,'/html/body/div[1]/div[2]/div[3]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div/div[2]/div')
for nme in name_tag:
    person_name.append(nme.text)

In [35]:
print(person_name)

['Bernard Arnault & family', 'WEALTH HISTORY']

In [36]:
#scraping net worth:-
nate_tag=driver.find_elements(By.XPATH,'/html/body/div[1]/div[2]/div[3]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div/div[3]/div')
for nte in nate_tag:
    net_worth.append(nte.text)

In [37]:
print(net_worth)

['$211 B']

In [38]:
#scraping  age :-
age_tag=driver.find_elements(By.XPATH,'/html/body/div[1]/div[2]/div[3]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div/div[4]/div')
for ag in age_tag:
    age.append(ag.text)

In [39]:
print(age)

['74']

In [40]:
#scraping city:-
city_tag=driver.find_elements(By.XPATH,'/html/body/div[1]/div[2]/div[3]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div/div[5]')
for cty in city_tag:
    citizenship.append(cty.text)

In [41]:
print(citizenship)

['France']

In [42]:
#scraping source:-
source_tag=driver.find_elements(By.XPATH,'/html/body/div[1]/div[2]/div[3]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div/div[6]/div/span')
for sou in source_tag:
    source.append(sou.text)

In [43]:
print(source)

['LVMH']

In [44]:
#scraping industry:-
industry_tag=driver.find_elements(By.XPATH,'/html/body/div[1]/div[2]/div[3]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div/div[7]/div')
for indus in industry_tag:
    industry.append(indus.text)

In [45]:
print(industry)

['Fashion & Retail']

In [47]:
#create first dataframe:-

df=pd.DataFrame({'Rank':rank[0:1],'Person Name':person_name[0:1],'Net Worth':net_worth[0:1],'Age':age[0:1],'Citizenship':citizenship[0:1],'Source':source[0:1],'Industry':industry[0:1]})
df

,Rank,Person Name,Net Worth,Age,Citizenship,Source,Industry
0,1,Bernard Arnault & family,$211 B,74,France,LVMH,Fashion & Retail

In [58]:
#Scraping required data from the web page
#Creating empty lists:-

rank=[]
person_name=[]
net_worth=[]
age=[]
citizenship=[]
source=[]
industry=[]

In [59]:
#scraping the data of rank of the billionaries:-
rank_tag=driver.find_elements(By.XPATH,'//div[@class="LeftRail_container__9pEea TableRow_leftRailTable__x2FIq"]/div[@class="TableRow_rowContainer__IC1Tv"]//div[@class="TableRow_row__L-0Km"]/div[1]')
for rnk in rank_tag:
    rank.append(rnk.text)

In [60]:
print(len(rank))

199

In [61]:
#scraping names:-
name_tag=driver.find_elements(By.XPATH,'//div[@class="LeftRail_container__9pEea TableRow_leftRailTable__x2FIq"]/div[@class="TableRow_rowContainer__IC1Tv"]//div[@class="TableRow_row__L-0Km"]/div[2]')
for nme in name_tag:
    person_name.append(nme.text)

In [62]:
print(len(person_name))

199

In [63]:
#scraping net_worths:-
nate_tag=driver.find_elements(By.XPATH,'//div[@class="LeftRail_container__9pEea TableRow_leftRailTable__x2FIq"]/div[@class="TableRow_rowContainer__IC1Tv"]//div[@class="TableRow_row__L-0Km"]/div[3]')
for nte in nate_tag:
    net_worth.append(nte.text)

In [64]:
print(len(net_worth))

199

In [65]:
#scraping Age:-
age_tag=driver.find_elements(By.XPATH,'//div[@class="LeftRail_container__9pEea TableRow_leftRailTable__x2FIq"]/div[@class="TableRow_rowContainer__IC1Tv"]//div[@class="TableRow_row__L-0Km"]/div[4]')
for ag in age_tag:
    age.append(ag.text)

In [66]:
print(len(age))

199

In [67]:
#scraping city:-
city_tag=driver.find_elements(By.XPATH,'//div[@class="LeftRail_container__9pEea TableRow_leftRailTable__x2FIq"]/div[@class="TableRow_rowContainer__IC1Tv"]//div[@class="TableRow_row__L-0Km"]/div[5]')
for cty in city_tag:
    citizenship.append(cty.text)

In [68]:
print(len(citizenship))

199

In [69]:
#scraping sources:-
source_tag=driver.find_elements(By.XPATH,'//div[@class="LeftRail_container__9pEea TableRow_leftRailTable__x2FIq"]/div[@class="TableRow_rowContainer__IC1Tv"]//div[@class="TableRow_row__L-0Km"]/div[6]')
for sou in source_tag:
    source.append(sou.text)

In [70]:
print(len(source))

199

In [71]:
#scraping industries:-
industry_tag=driver.find_elements(By.XPATH,'//div[@class="LeftRail_container__9pEea TableRow_leftRailTable__x2FIq"]/div[@class="TableRow_rowContainer__IC1Tv"]//div[@class="TableRow_row__L-0Km"]/div[7]')
for indus in industry_tag:
    industry.append(indus.text)

In [72]:
print(len(industry))

199

In [73]:
#Create second dataframe:-

df1=pd.DataFrame({'Rank':rank,'Person Name':person_name,'Net Worth':net_worth,'Age':age,'Citizenship':citizenship,'Source':source,'Industry':industry})
df1

,Rank,Person Name,Net Worth,Age,Citizenship,Source,Industry
0,2,Elon Musk,$180 B,51,United States,"Tesla, SpaceX",Automotive
1,3,Jeff Bezos,$114 B,59,United States,Amazon,Technology
2,4,Larry Ellison,$107 B,78,United States,Oracle,Technology
3,5,Warren Buffett,$106 B,92,United States,Berkshire Hathaway,Finance & Investments
4,6,Bill Gates,$104 B,67,United States,Microsoft,Technology
...,...,...,...,...,...,...,...
194,195,Jin Baofang,$9.6 B,70,China,Solar panels,Energy
195,195,Luo Liguo & family,$9.6 B,67,China,Chemicals,Manufacturing
196,195,Marijke Mars,$9.6 B,58,United States,"Candy, pet food",Food & Beverage
197,195,Pamela Mars,$9.6 B,62,United States,"Candy, pet food",Food & Beverage
198,195,Valerie Mars,$9.6 B,64,United States,"Candy, pet food",Food & Beverage

In [88]:
#concat both dataframes:-

df2=pd.concat([df,df1])

In [89]:
print(df2)

    Rank               Person Name Net Worth Age    Citizenship  \
0      1  Bernard Arnault & family    $211 B  74         France
0      2                 Elon Musk    $180 B  51  United States
1      3                Jeff Bezos    $114 B  59  United States
2      4             Larry Ellison    $107 B  78  United States
3      5            Warren Buffett    $106 B  92  United States
..   ...                       ...       ...  ..            ...
194  195               Jin Baofang    $9.6 B  70          China
195  195        Luo Liguo & family    $9.6 B  67          China
196  195              Marijke Mars    $9.6 B  58  United States
197  195               Pamela Mars    $9.6 B  62  United States
198  195              Valerie Mars    $9.6 B  64  United States

                 Source               Industry
0                  LVMH       Fashion & Retail
0         Tesla, SpaceX             Automotive
1                Amazon             Technology
2                Oracle             Technology
3    Berkshire Hathaway  Finance & Investments
..                  ...                    ...
194        Solar panels                 Energy
195           Chemicals          Manufacturing
196     Candy, pet food        Food & Beverage
197     Candy, pet food        Food & Beverage
198     Candy, pet food        Food & Beverage

[200 rows x 7 columns]

#Question no. 8:- Write a program to extract at least 500 Comments, Comment upvote and time when comment was posted 
from any YouTube Video

In [27]:

# Import the required modules
import requests
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.common.keys import Keys
import time

In [28]:
#connecting to web driver:-
driver=webdriver.Chrome()

In [29]:
#go to webpage:-
driver.get("https://www.youtube.com/")

In [30]:
#finding element for search box:-
search_bar=driver.find_element(By.XPATH,"//div[@class='ytd-searchbox-spt']/input")
#entering video name:-
search_bar.send_keys("GOT")  
time.sleep(2)

In [31]:
#clicking on search button:-
search_btn=driver.find_element(By.ID,'search-icon-legacy')
search_btn.click()
time.sleep(2)

In [32]:
#clicking on first video:-
video= driver.find_element(By.XPATH,"/html/body/ytd-app/div[1]/ytd-page-manager/ytd-search/div[1]/ytd-two-column-search-results-renderer/div/ytd-section-list-renderer/div[2]/ytd-item-section-renderer/div[3]/ytd-video-renderer[6]/div[1]/div/div[1]/div/h3/a/yt-formatted-string")
video.click()

In [33]:
#1000 times we scroll down by 10000 in order to generate more comments:-
for _ in range(1000):
    driver.execute_script("window.scrollBy(0,10000)")

In [48]:
#creating empty lists:-
comments=[]
comment_time=[]
Time=[]
No_of_likes=[]

In [49]:
#scrape comments:-
cm=driver.find_elements(By.ID,'content-text')
for i in cm:
    if i.text is None:
        comments.append("--")
    else:
        comments.append(i.text)
time.sleep(3)

In [50]:
#scrape time when comment was posted:-
tm=driver.find_elements(By.XPATH,'//a[@class="yt-simple-endpoint style-scope yt-formatted-string"]')
for i in tm:
    Time.append(i.text)
    
for i in range(0,len(Time),2):
    comment_time.append(Time[i])
time.sleep(3)

In [51]:
#scrape the comment likes:-
like=driver.find_elements(By.ID,"vote-count-middle")
for i in like:
    if i.text is None:
        No_of_likes.append("--")
    else:
        No_of_likes.append(i.text)
time.sleep(3)

In [54]:
#creating dataframe for scraped data:-
Youtube=pd.DataFrame({})
Youtube['Comment']=comments[:500]
Youtube['Comment Time']=comment_time[:500]
Youtube['Comment Upvotes']=No_of_likes[:500]
Youtube

,Comment,Comment Time,Comment Upvotes
0,It's still immencely funny how the moment Daen...,,5.9K
1,"I hate how Danny had a great conquering life, ...",,3.3K
2,"""Well...Euron kind of forgot how to aim at dra...",,5.4K
3,Seasons 1-7: “Loose!” when releasing an arrow....,,645
4,Drogon destroying those ballistas is probably ...,,5.6K
...,...,...,...
495,One of the most satisfying scenes ever,2 years ago,
496,All if a sudden dragon fire explodes stone,11 months ago,
497,So they managed to kill a dragon and push anot...,10 months ago,
498,Dany was the Princess that was promised. Let’s...,7 months ago,1
499,Random soldier FIRE!!!!\nDrogon.... as you wish,1 year ago,

#Question no. 9:-Write a python program to scrape a data for all available Hostels from https://www.hostelworld.com/ in 
“London” location. You have to scrape hostel name, distance from city centre, ratings, total reviews, overall 
reviews, privates from price, dorms from price, facilities and property description.

In [31]:
# Import the required modules
import requests
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.common.keys import Keys
import time
from selenium.common.exceptions import NoSuchElementException

In [32]:
#connecting to web driver:-
driver=webdriver.Chrome()

In [33]:
#go to webpage:-
driver.get("https://www.hostelworld.com/st/hostels/europe/england/london")

In [34]:
#search the page:-

search_btn=driver.find_elements(By.XPATH,'/div[@class="icon-container"]')

In [35]:
#Creating empty list and find required data:-
hostel_name=[]
distance=[]
pvt_prices=[]
dorms_price=[]
rating=[]
reviews=[]
over_all=[]
facilities=[]
description=[]

In [36]:
#scraping the required information:-
for i in driver.find_elements(By.XPATH,"/html/body/div[3]/div/div/div[2]/div[2]/div[1]/div/div/div[4]"):

    
    try:
        name_tag=driver.find_elements(By.XPATH,'//div[@class="property-name"]/span')
        for i in name_tag:
            hostel_name.append(i.text)
    except NoSuchElementException:
        hostel_name.append("-")
        
    try:
        distance_tag=driver.find_elements(By.XPATH,'//span[@class="distance-description"]')
        for i in distance_tag:
            distance.append(i.text)
    except NoSuchElementException:
        distance.append("-")
        
        
    try:
        dorms_tag=driver.find_elements(By.XPATH,'//div[2][@class="property-accommodation-price"]//strong[1][@class="current"]')
        for i in dorms_tag:
            dorms_price.append(i.text)
    except NoSuchElementException:
        dorms_price.append("-")
        
    try:
        rating_tag=driver.find_elements(By.XPATH,'//a[@class="property-card-container horizontal"]//span[@class="number"]')
        for i in rating_tag:
            rating.append(i.text)
    except NoSuchElementException:
        rating.append("-")
        
    try:
        reviews_tag=driver.find_elements(By.XPATH,'//div[@class="review"]')
        for i in reviews_tag:
            reviews.append(i.text)
    except NoSuchElementException:
        reviews.append("-")
        
    try:
        over_tag=driver.find_elements(By.XPATH,'//a[@class="property-card-container horizontal"]//span[@class="keyword"]')
        for i in over_tag:
            over_all.append(i.text)
    except NoSuchElementException:
        over_all.append("-")

In [37]:
#scrape all product urls:-
product_urls=[]
#scraping urls:-
url=driver.find_elements(By.XPATH,'//a[@class="property-card-container horizontal"]')
for i in url:
    product_urls.append(i.get_attribute("href"))

In [38]:
len(product_urls)

30

In [39]:
#scraping remaining information:-

for url in product_urls:
    driver.get(url)
    time.sleep(2)
        
    try:
        facil_tag=driver.find_element(By.XPATH,'//ul[@class="facility-sections"]/li[1]')
        facilities.append(facil_tag.text)
    except NoSuchElementException:
        facilities.append("-")
        
    
    try:
        des_tag=driver.find_element(By.XPATH,'//div[@class="content collapse-content"]')
        description.append(des_tag.text)
    except NoSuchElementException:
        description.append("-")

In [41]:
print(len(facilities))

30

In [42]:
print(len(description))

30

In [43]:
#create dataframe:-
df=pd.DataFrame({'Hostel Name':hostel_name,'Distance':distance,'Dorms price':dorms_price,'Rating':rating,'Reviews':reviews,'Over All':over_all,'Facilities':facilities,'Description':description})

df

,Hostel Name,Distance,Dorms price,Rating,Reviews,Over All,Facilities,Description
0,Wombat's City Hostel London,- 3.6km from city centre,"₹2,145",9.1,(15929),Superb,Free\nLinen Included Free City Maps Free WiFi ...,A safe haven in the middle of the metropolis: ...
1,Palmers Lodge - Swiss Cottage,- 6.5km from city centre,"₹2,089",8.8,(15982),Fabulous,Free\nLinen Included Free WiFi Free Internet A...,"Whether you're a backpacker, flash-packer or a..."
2,St Christopher's Village,- 1.8km from city centre,"₹1,347",7.8,(12882),Very Good,Free\nLinen Included Free WiFi Free Internet A...,St Christopher's Inn at The Village in London ...
3,Urbany Hostel London,- 5.4km from city centre,"₹2,255",9.5,(1131),Superb,Free\nLinen Included Free WiFi,"Welcome to Urbany Hostel London, our first int..."
4,Onefam Notting Hill,- 5.5km from city centre,"₹2,399",9.6,(2608),Superb,Free\nLinen Included Free WiFi Free Internet A...,The perfect place for solo travelers to connec...
5,Generator London,- 3km from city centre,"₹2,666",7.5,(8091),Very Good,Free\nLinen Included Free City Maps Free WiFi ...,Generator London is a design hotel-hostel loca...
6,Onefam Waterloo,- 0.7km from city centre,"₹2,234",9.6,(153),Superb,Free\nLinen Included Free WiFi Free Internet A...,Come join us at our newest Onefam location in ...
7,Astor Hyde Park,- 4.3km from city centre,"₹1,574",8.2,(12332),Fabulous,Free\nLinen Included Free City Maps Free WiFi ...,Located in the most beautiful and charming nei...
8,Safestay London Elephant & Castle,- 1.7km from city centre,"₹2,155",7.3,(5285),Very Good,Free\nLinen Included Free WiFi,Safestay at Elephant & Castle is ideal if you ...
9,Astor Museum Inn,- 2.2km from city centre,"₹1,847",8.4,(9459),Fabulous,Free\nLinen Included Free City Maps Free WiFi,With the British Museum literally on its doors...
10,No.8 Seven Sisters,- 9km from city centre,"₹1,040",7.7,(4181),Very Good,Free\nLinen Included Free WiFi,"For Great Facilities, Comfort & Affordability ..."
11,Clink261,- 3.2km from city centre,"₹1,646",8.0,(524),Fabulous,Free\nLinen Included Free City Maps Free WiFi,Welcome to Clink261!\n\nClink261 is a comforta...
12,No.8 Willesden Hostel London,- 10km from city centre,₹988,7.1,(5208),Very Good,Free\nLinen Included Free WiFi,At No.8 we take pride in our Customer Service ...
13,Smart Russell Square Hostel,- 2.6km from city centre,"₹1,355",7.6,(10213),Very Good,Free\nLinen Included Free City Maps Free WiFi ...,Loved this place. Only thing I’d say is the sh...
14,Safestay London Kensington Holland Park,- 5.8km from city centre,"₹1,260",6.9,(1788),Good,Free\nLinen Included Free WiFi,Safestay Holland Park\n\nSafestay Holland Park...
15,The Walrus Hostel,- 0.2km from city centre,"₹1,921",7.9,(4304),Very Good,Free\nLinen Included Free City Maps Free WiFi ...,The Walrus Hostel is the ideal choice for thos...
16,Smart Hyde Park Inn Hostel,- 5km from city centre,"₹1,261",7.7,(6803),Very Good,Free\nLinen Included Free City Maps Free WiFi ...,I stayed at this hostel solo travelling for th...
17,YHA London Oxford Street,- 2.1km from city centre,"₹2,613",9.0,(4704),Superb,Free\nLinen Included Free WiFi,A quiet hideaway from the bustle of the busies...
18,Queen Elizabeth Chelsea,- 5.7km from city centre,"₹1,272",7.5,(3692),Very Good,Free\nLinen Included Free City Maps Free WiFi ...,PLEASE NOTE WE ONLY ACCEPT GUESTS FROM THE AGE...
19,Destinations Hostels @ The Gallery,- 1.7km from city centre,"₹3,131",9.1,(320),Superb,Free\nFree Breakfast Linen Included Free City ...,"We are back, we previously operated near Londo..."
20,Prime Backpackers Angel,- 3.6km from city centre,"₹3,012",8.7,(873),Fabulous,Free\nLinen Included Free City Maps Towels Inc...,The hostel is housed in a historic building in...
21,Hostelle - women only hostel London,- 5.1km from city centre,"₹2,056",8.8,(122),Fabulous,Free\nLinen Included Free City Maps Free WiFi ...,Hostelle is the first and only all-women hoste...
22,London Backpackers,- 11.9km from city centre,"₹1,463",8.1,(4568),Fabulous,Free\nLinen Included Free City Maps Free WiFi ...,IMPORTANT NOTICE: \n\nThis hostel is for 18 - ...
23,Smart Camden Inn Hostel,- 4.4km from city centre,"₹1,872",8.4,(3145),Fabulous,Free\nLinen Included Free City Maps Free WiFi,"Located in the middle of Camden Town, we’re th..."
24,Kabannas London St Pancras,- 3.3km from city centre,"₹2,258",8.2,(2978),Fabulous,Free\nLinen Included Free City Maps Free WiFi,Located opposite Kings Cross/St Pancras Intern...
25,Astor Kensington,- 4.9km from city centre,"₹1,568",8.5,(6596),Fabulous,Free\nLinen Included Free City Maps Free WiFi,"Located a short walk from Notting Hill, Hyde P..."
26,St Christopher's Inn - London Bridge,- 1.8km from city centre,"₹1,661",8.0,(3605),Fabulous,Free\nLinen Included Free City Maps Free WiFi ...,Base yourself in the electric area of London B...
27,Astor Victoria,- 1.8km from city centre,"₹1,668",7.2,(15100),Very Good,Free\nLinen Included Free City Maps Free WiFi ...,With Victoria Station and Buckingham Palace a ...
28,St Christopher's Hammersmith,- 7.5km from city centre,"₹1,138",7.5,(4392),Very Good,Free\nLinen Included Free City Maps Free WiFi ...,I had a fantastic stay at St Christopher’s Inn...
29,Phoenix Hostel,- 4.2km from city centre,"₹1,296",6.3,(4625),Good,Free\nLinen Included Free City Maps Free WiFi ...,"The Phoenix Bar & Hostel, housed in a homely E..."